apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: single-node-mysql-pvc
  namespace: single-node-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
