---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-node-mysql
  namespace: single-node-mysql
spec:
  selector:
    matchLabels:
      app: single-node-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: single-node-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: single-node-mysql-pvc
